

services:

  part_6:


    image: barkopen:part_5_1
    container_name: part_6
    tty: true                                         # Определяет, будет ли ассоциирован TTY-терминал с контейнером
    user: root                                        # Устанавливает пользователя по умолчанию внутри контейнера


  nginx-proxy:
    image: nginx
    container_name: nginx_proxy                       # Устанавливает имя контейнера
    depends_on:
      - part_6                                        # Указывает, что контейнер nginx-proxy зависит от контейнера server-part-6
    ports:
      - "80:8080"                                     # Пробрасывает порт 80 хоста на порт 8080 контейнера
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   # Монтирует файл конфигурации nginx.conf в контейнер
    tty: true                                         # Определяет, будет ли ассоциирован TTY-терминал с контейнером
    user: root                                        # Устанавливает пользователя по умолчанию внутри контейнера